name: yt-streamer
version: 0.3
vendor: Pedro Coca <Pedro.Coca@canonical.com>
config: ./config.py

services:
  yt-streamer:
    start: bin/yt-streamer.sh
    description: A simple video stream to youtube
    security-override:
      apparmor: security/apparmor.override
      seccomp: security/seccomp.override

summary: A simple video stream to youtube
description: A simple video stream to youtube
icon: yt-streamer_icon.png


parts:
  yt-streamer:
    plugin: copy
    files:
        yt-streamer.sh: bin/yt-streamer.sh
        ffmpeg: bin/ffmpeg
        config.py: config.py
