name: youtube-streamer
version: 0.2
config: ./config.py

apps:
  youtube-streamer:
    command: bin/youtube-streamer
    daemon: simple
    uses: [cam-transcode]

uses:
  cam-transcode:
    type: migration-skill
    security-override:
      apparmor: security/apparmor.override
      seccomp: security/seccomp.override

summary: A simple video stream to youtube
description: A simple video stream to youtube
icon: youtube-streamer_icon.png

parts:
  ffmpeg:
    plugin: nil
    stage-packages:
      - ffmpeg
      - libstdc++6
    snap:
      - lib
      - usr/bin/ffmpeg
      - usr/lib
  youtube-streamer:
    plugin: copy
    files:
        youtube-streamer: bin/youtube-streamer
        config.py: config.py
