name: youtube-streamer-demo
version: 0.1.1
vendor: Didier Roche <didrocks@ubuntu.com>, Pedro Coca <Pedro.Coca@canonical.com>
config: ./config.py

services:
  youtube-streamer:
    start: bin/youtube-streamer
    description: A simple video stream to youtube
    security-override:
      apparmor: security/apparmor.override
      seccomp: security/seccomp.override

summary: A simple video stream to youtube
description: A simple video stream to youtube
icon: youtube-streamer_icon.png


parts:
  ffmpeg:
    plugin: nil
    stage-packages:
      - ffmpeg
      - libstdc++6
    snap:
      - lib
      - usr/bin/ffmpeg
      - usr/lib
  youtube-streamer:
    plugin: copy
    files:
        youtube-streamer: bin/youtube-streamer
        config.py: config.py
