name: youtube-streamer
version: 0.2
summary: A simple video stream to youtube
description: A simple video stream to youtube
icon: youtube-streamer_icon.png
config: ./config.py

apps:
  youtube-streamer:
    command: bin/youtube-streamer
    daemon: simple
    plugs: [cam-transcode]

plugs:
  cam-transcode:
    interface: old-security
    security-override:
      apparmor: security/apparmor.override
      seccomp: security/seccomp.override

parts:
  ffmpeg:
    plugin: nil
    stage-packages:
      - ffmpeg
      - libstdc++6
    snap:
      - lib
      - usr/bin/ffmpeg
      - usr/lib
  youtube-streamer:
    plugin: copy
    files:
        youtube-streamer: bin/youtube-streamer
        config.py: config.py
