name: face-detection
version: 0.2
summary: Demo for Face Detection statistics
description: |
  This demo shows face detection statics parameterized to take a picture through a webcam X seconds
  (timing between pictures can be defined in $SNAP_DATA/settings). Report results through a web interface
  on 8042 port (configurable as well).

apps:
  facedetectionweb:
    command: bin/facedetection.exports
    plugs: [unconfined-plug]
    daemon: simple

plugs:
  unconfined-plug:
    interface: old-security
    security-template: unconfined

parts:
  demo:
    plugin: copy
    files:
      'bin/*': 'bin/'
      'logic.xml': 'logic.xml'
      'facedetection': 'facedetection'
    stage-packages:
     - python-dev
     - python-opencv
     - python-numpy
     - python-yaml
